modLoader="javafml"
loaderVersion="[47,)"
license="All rights reserved"

[[mods]] #mandatory
modId="difficultraids"
version="${file.jarVersion}"
displayName="Difficult Raids"
displayURL="https://www.curseforge.com/minecraft/mc-mods/difficult-raids-stronghold-survival-edition" #optional
logoFile="logo.png" #optional
credits="LDawsonM2012 for the 1.20.1 port. See CurseForge page for a list of all texture artists!" #optional
authors="CalculusMaster" #optional
description='''
Do you like Raids? Do you think they're too easy?
Difficult Raids adds higher difficulty options for Raids as well as new Illagers to challenge you.
Higher difficulty raids offer greater rewards.
Are you up for the challenge?
'''

[[dependencies.difficultraids]] #optional
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.difficultraids]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,1.20.2)"
    ordering="NONE"
    side="BOTH"
